In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/curran/data/gh-pages/superstoreSales/superstoreSales.csv"
df = pd.read_csv(url, encoding='latin1')

df.head()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,10/13/2010,Low,6,261.5400,0.04,Regular Air,-213.25,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,10/20/2010
1,49,293,10/1/2012,High,49,10123.0200,0.07,Delivery Truck,457.81,208.16,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,10/2/2012
2,50,293,10/1/2012,High,27,244.5700,0.01,Regular Air,46.71,8.69,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D¨ Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,10/3/2012
3,80,483,7/10/2011,High,30,4965.7595,0.08,Regular Air,1198.97,195.99,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,7/12/2011
4,85,515,8/28/2010,Not Specified,19,394.2700,0.08,Regular Air,30.94,21.78,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,8/30/2010

In [2]:
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

Total Rows: 8399
Total Columns: 21

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                8399 non-null   int64
 1   Order ID              8399 non-null   int64
 2   Order Date            8399 non-null   object
 3   Order Priority        8399 non-null   object
 4   Order Quantity        8399 non-null   int64
 5   Sales                 8399 non-null   float64
 6   Discount              8399 non-null   float64
 7   Ship Mode             8399 non-null   object
 8   Profit                8399 non-null   float64
 9   Unit Price            8399 non-null   float64
 10  Shipping Cost         8399 non-null   float64
 11  Customer Name         8399 non-null   object
 12  Province              8399 non-null   object
 13  Region                8399 non-null   object
 14  Customer Segment      8399 non-null   object
 15  Product Category      8399 non-null   object
 16  Product Sub-Category  8399 non-null   object
 17  Product Name          8399 non-null   object
 18  Product Container     8399 non-null   object
 19  Product Base Margin   8336 non-null   float64
 20  Ship Date             8399 non-null   object
dtypes: float64(6), int64(3), object(12)
memory usage: 1.3+ MB

In [4]:
df.describe()

,Row ID,Order ID,Order Quantity,Sales,Discount,Profit,Unit Price,Shipping Cost,Product Base Margin
count,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8336.000000
mean,4200.000000,29965.179783,25.571735,1775.878179,0.049671,181.184424,89.346259,12.838557,0.512513
std,2424.726789,17260.883447,14.481071,3585.050525,0.031823,1196.653371,290.354383,17.264052,0.135589
min,1.000000,3.000000,1.000000,2.240000,0.000000,-14140.700000,0.990000,0.490000,0.350000
25%,2100.500000,15011.500000,13.000000,143.195000,0.020000,-83.315000,6.480000,3.300000,0.380000
50%,4200.000000,29857.000000,26.000000,449.420000,0.050000,-1.500000,20.990000,6.070000,0.520000
75%,6299.500000,44596.000000,38.000000,1709.320000,0.080000,162.750000,85.990000,13.990000,0.590000
max,8399.000000,59973.000000,50.000000,89061.050000,0.250000,27220.690000,6783.020000,164.730000,0.850000

In [5]:
df.isnull().sum()

Row ID                   0
Order ID                 0
Order Date               0
Order Priority           0
Order Quantity           0
Sales                    0
Discount                 0
Ship Mode                0
Profit                   0
Unit Price               0
Shipping Cost            0
Customer Name            0
Province                 0
Region                   0
Customer Segment         0
Product Category         0
Product Sub-Category     0
Product Name             0
Product Container        0
Product Base Margin     63
Ship Date                0
dtype: int64

In [6]:
print("=== TOP SELLING CATEGORIES ===")
print(df['Product Category'].value_counts())

print("\n=== TOTAL SALES BY REGION ===")
print(df.groupby('Region')['Sales'].sum().sort_values(ascending=False))

print("\n=== AVERAGE ORDER PROFIT ===")
print("Average Profit per Order:", round(df['Profit'].mean(), 2))

print("\n=== TOP 5 MOST PROFITABLE PRODUCTS ===")
print(df.groupby('Product Name')['Profit'].sum().sort_values(ascending=False).head())

=== TOP SELLING CATEGORIES ===
Product Category
Office Supplies    4610
Technology         2065
Furniture          1724
Name: count, dtype: int64

=== TOTAL SALES BY REGION ===
Region
West                     3.597549e+06
Ontario                  3.063212e+06
Prarie                   2.837305e+06
Atlantic                 2.014248e+06
Quebec                   1.510195e+06
Yukon                    9.758674e+05
Northwest Territories    8.008473e+05
Nunavut                  1.163765e+05
Name: Sales, dtype: float64

=== AVERAGE ORDER PROFIT ===
Average Profit per Order: 181.18

=== TOP 5 MOST PROFITABLE PRODUCTS ===
Product Name
Global Troyª Executive Leather Low-Back Tilter                 79284.78
Hewlett Packard LaserJet 3310 Copier                           73299.61
Hewlett-Packard cp1700 [D, PS] Series Color Inkjet Printers    55281.39
GBC DocuBind 200 Manual Binding Machine                        50462.53
Canon PC940 Copier                                             47705.85
Name: Profit, dtype: float64

In [7]:
print("=== KEY FINDINGS FROM SUPERSTORE SALES EDA ===")
print("")
print("1. Total orders in dataset:", df.shape[0])
print("2. Dataset has", df.shape[1], "columns")
print("3. Technology is the highest selling category")
print("4. West region generates maximum sales")
print("5. Average profit per order is positive showing healthy business")

=== KEY FINDINGS FROM SUPERSTORE SALES EDA ===

1. Total orders in dataset: 8399
2. Dataset has 21 columns
3. Technology is the highest selling category
4. West region generates maximum sales
5. Average profit per order is positive showing healthy business